// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqXpOdQphjdSaMr_QdhIi_XJLo4WOPesM',
    appId: '1:598667084465:web:26c01cc205ad14da675890',
    messagingSenderId: '598667084465',
    projectId: 'we-chat-910e8',
    authDomain: 'we-chat-910e8.firebaseapp.com',
    storageBucket: 'we-chat-910e8.appspot.com',
    measurementId: 'G-2VZG6QF71M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHhgpn91uuktmwvncFH2jsmkLfxy3qwaQ',
    appId: '1:598667084465:android:26bcef7b2057ed0d675890',
    messagingSenderId: '598667084465',
    projectId: 'we-chat-910e8',
    storageBucket: 'we-chat-910e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ukdo58bcVPv1-IE4UTWZ4bSzbAy37Wc',
    appId: '1:598667084465:ios:83b4a29d43a00f4b675890',
    messagingSenderId: '598667084465',
    projectId: 'we-chat-910e8',
    storageBucket: 'we-chat-910e8.appspot.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ukdo58bcVPv1-IE4UTWZ4bSzbAy37Wc',
    appId: '1:598667084465:ios:83b4a29d43a00f4b675890',
    messagingSenderId: '598667084465',
    projectId: 'we-chat-910e8',
    storageBucket: 'we-chat-910e8.appspot.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqXpOdQphjdSaMr_QdhIi_XJLo4WOPesM',
    appId: '1:598667084465:web:1ea1df3db15082f9675890',
    messagingSenderId: '598667084465',
    projectId: 'we-chat-910e8',
    authDomain: 'we-chat-910e8.firebaseapp.com',
    storageBucket: 'we-chat-910e8.appspot.com',
    measurementId: 'G-6WCXWG69JG',
  );
}
